name: gia_pha_mobile
description: "Gia Pha mobile project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1
  flutter: ">=3.35.6 <3.36.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  nb_utils: ^7.1.4
  image_picker: ^1.1.2
  package_info_plus: ^8.3.0
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.1
  org_chart: ^5.0.0
  flutter_vector_icons: ^2.0.0
  calendar_view: ^1.4.0
  intl: ^0.20.0
  simple_gallery: ^0.0.3
  fl_chart: ^1.0.0
  http: ^1.5.0
  dio_cookie_manager: ^3.3.0
  dio: ^5.9.0
  cookie_jar: ^4.0.8
  passkeys: ^2.17.3
  file_saver: ^0.3.1
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  flutter_html: ^3.0.0
  flutter_html_iframe: ^3.0.0
  qr_code_scanner: ^0.4.0
  flutter_svg: ^2.0.10+1
  qr_flutter: ^4.1.0
  mobile_scanner: ^5.1.0

dependency_overrides:
  pact_dart:
    git:
      url: https://github.com/tienvx/pact_dart.git
      ref: all
  flutter_html_iframe: #^3.0.0
    git:
      url: https://github.com/hnvn/flutter_html.git
      path: packages/flutter_html_iframe

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  test: ^1.25.15
  pact_dart: ^0.8.0


flutter:
  uses-material-design: true
  assets:
    - images/flags/
